# Case-sensitive paths to include during linting. Directory paths supplied on the
# command line will be ignored.
included: #paths to include during linting. '--path' is ignored if present.
 - ../Sources/CountriesFlags

excluded: # case-sensitive paths to ignore during linting. Takes precedence over `included`
 - ../Sources/CountriesFlagsObjC
 
disabled_rules: # rule identifiers to exclude from running
  - todo
  - function_body_length
  
opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - attributes
  - closure_spacing
  - collection_alignment
  - direct_return
  - empty_count
  - empty_xctest_method
  - file_types_order # Specifies how the types within a file should be ordered.
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
#  - no_magic_numbers
  - no_space_in_method_call
  - operator_usage_whitespace
  - type_contents_order
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - yoda_condition

identifier_name:
  min_length: 2
