# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: UnitTests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#standard-github-hosted-runners-for-public-repositories
    runs-on: macos-15
    
    name: iOS Unit Testing

    steps:
# https://github.com/actions/checkout
    - uses: actions/checkout@v4
#    - name: Build
#      run: swift build -v
#    - name: Run tests
#      run: swift test -v
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.4.app && /usr/bin/xcodebuild -version
#    - name: Download iOS Simulator Runtime
#      run: sudo xcodebuild -downloadPlatform iOS
    - name: List available simulators (debug)
      run: xcrun simctl list devices
    - name: Build and run swift tests
      run: xcodebuild test -scheme CountriesFlags -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.4' | xcpretty && exit ${PIPESTATUS[0]}
    - name: Build and run objective-c tests
      run: xcodebuild test -scheme CountriesFlagsObjC -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.4' | xcpretty && exit ${PIPESTATUS[0]}
